/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Check: typeof import('./src/components/Check.vue')['default']
    Fivesite: typeof import('./src/components/Fivesite.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    Reservation: typeof import('./src/components/Reservation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Threesite: typeof import('./src/components/Threesite.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
